//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoPromocao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPOM_PROMOCIONAL
    {
        public int ID_CUPOM { get; set; }
        public string NOME_PRODUTO { get; set; }
        public decimal VALOR { get; set; }
        public System.DateTime DATA_INICIO { get; set; }
        public Nullable<System.DateTime> DATA_FIM { get; set; }
        public string ESTADO { get; set; }
        public string CIDADE { get; set; }
        public string BAIRRO { get; set; }
        public string RUA { get; set; }
        public Nullable<int> NUMERO { get; set; }
    }
}
